#ifndef SURFACERECONSTURCTION_GLOBAL_H
#define SURFACERECONSTURCTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SURFACERECONSTURCTION_LIBRARY)
#  define SURFACERECONSTURCTION_EXPORT Q_DECL_EXPORT
#else
#  define SURFACERECONSTURCTION_EXPORT Q_DECL_IMPORT
#endif

#endif // SURFACERECONSTURCTION_GLOBAL_H
