#ifndef SURFACECONSTURCTION_GLOBAL_H
#define SURFACECONSTURCTION_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SURFACECONSTURCTION_LIBRARY)
#  define SURFACECONSTURCTION_EXPORT Q_DECL_EXPORT
#else
#  define SURFACECONSTURCTION_EXPORT Q_DECL_IMPORT
#endif

#endif // SURFACECONSTURCTION_GLOBAL_H
